import React, { useState } from 'react';
import Button from './Button';

function QuizModal({ quiz, onClose }) {
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);

  if (!quiz || !quiz.questions) return null;

  const handleAnswer = (questionId, answer) => {
    setAnswers({
      ...answers,
      [questionId]: answer
    });
  };

  const handleSubmit = () => {
    let correct = 0;
    quiz.questions.forEach(q => {
      if (answers[q.id] === q.correctAnswer) {
        correct++;
      }
    });
    setScore(correct);
    setSubmitted(true);
  };

  const getOptionStyle = (questionId, optionLetter, isCorrect) => {
    if (!submitted) return {};
    
    if (answers[questionId] === optionLetter) {
      if (isCorrect) {
        return {
          background: '#d4edda',
          borderColor: '#28a745'
        };
      } else {
        return {
          background: '#f8d7da',
          borderColor: '#dc3545'
        };
      }
    }
    
    if (isCorrect) {
      return {
        background: '#d4edda',
        borderColor: '#28a745'
      };
    }
    
    return {};
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0,0,0,0.8)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
        padding: '20px',
        overflowY: 'auto'
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: 'white',
          borderRadius: '16px',
          maxWidth: '800px',
          width: '100%',
          maxHeight: '90vh',
          overflowY: 'auto',
          padding: '30px',
          position: 'relative'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          style={{
            position: 'absolute',
            top: '15px',
            right: '20px',
            background: 'none',
            border: 'none',
            fontSize: '28px',
            cursor: 'pointer',
            color: '#666',
            fontWeight: 'bold'
          }}
        >
          ✕
        </button>

        <div style={{ textAlign: 'center', marginBottom: '20px' }}>
          <h2 style={{ color: '#667eea', marginBottom: '5px' }}>
            📝 AI-Generated Quiz
          </h2>
          <p style={{ color: '#666' }}>
            Topic: <strong>{quiz.topic}</strong>
          </p>
          {quiz.fallback && (
            <p style={{ color: '#ff9800', fontSize: '12px', marginTop: '5px' }}>
              🤖 Using smart fallback questions (AI service optimized)
            </p>
          )}
          {!quiz.fallback && (
            <p style={{ color: '#4caf50', fontSize: '12px', marginTop: '5px' }}>
              ✨ Generated by Google Gemini AI
            </p>
          )}
        </div>

        {submitted && (
          <div
            style={{
              background: score === quiz.totalQuestions ? '#d4edda' : '#fff3cd',
              padding: '15px',
              borderRadius: '10px',
              marginBottom: '20px',
              textAlign: 'center'
            }}
          >
            <h3 style={{ margin: 0, color: score === quiz.totalQuestions ? '#155724' : '#856404' }}>
              🎯 Your Score: {score}/{quiz.totalQuestions}
            </h3>
            {score === quiz.totalQuestions && (
              <p style={{ margin: '10px 0 0 0', color: '#155724' }}>
                🎉 Perfect! Excellent understanding of {quiz.topic}!
              </p>
            )}
            {score < quiz.totalQuestions && (
              <p style={{ margin: '10px 0 0 0', color: '#856404' }}>
                💡 Review the explanations below to improve your knowledge!
              </p>
            )}
          </div>
        )}

        {quiz.questions.map((q, idx) => {
          const optionLetters = ['A', 'B', 'C', 'D'];
          
          return (
            <div
              key={q.id}
              style={{
                marginBottom: '30px',
                padding: '20px',
                background: '#f9f9f9',
                borderRadius: '12px',
                border: '1px solid #e0e0e0'
              }}
            >
              <h4 style={{ margin: '0 0 15px 0', color: '#333', fontSize: '16px' }}>
                <span style={{ 
                  background: '#667eea', 
                  color: 'white', 
                  padding: '2px 10px', 
                  borderRadius: '20px',
                  display: 'inline-block',
                  marginRight: '10px',
                  fontSize: '14px'
                }}>
                  Q{idx + 1}
                </span>
                {q.question}
              </h4>
              
              <div style={{ marginTop: '15px' }}>
                {q.options.map((option, optIdx) => {
                  const optionLetter = optionLetters[optIdx];
                  const isCorrect = optionLetter === q.correctAnswer;
                  const isSelected = answers[q.id] === optionLetter;
                  
                  return (
                    <label
                      key={optIdx}
                      style={{
                        display: 'flex',
                        alignItems: 'flex-start',
                        margin: '12px 0',
                        padding: '12px',
                        background: getOptionStyle(q.id, optionLetter, isCorrect).background || '#fff',
                        borderRadius: '8px',
                        cursor: !submitted ? 'pointer' : 'default',
                        border: `2px solid ${getOptionStyle(q.id, optionLetter, isCorrect).borderColor || '#e0e0e0'}`,
                        transition: 'all 0.2s'
                      }}
                    >
                      <input
                        type="radio"
                        name={`question-${q.id}`}
                        value={optionLetter}
                        checked={answers[q.id] === optionLetter}
                        onChange={() => !submitted && handleAnswer(q.id, optionLetter)}
                        disabled={submitted}
                        style={{ marginRight: '12px', marginTop: '2px' }}
                      />
                      <div style={{ flex: 1 }}>
                        <strong style={{ color: '#667eea' }}>{optionLetter})</strong>{' '}
                        <span style={{ color: '#333' }}>{option}</span>
                        {submitted && isCorrect && (
                          <span style={{ marginLeft: '10px', color: '#28a745' }}>✓ Correct!</span>
                        )}
                        {submitted && isSelected && !isCorrect && (
                          <span style={{ marginLeft: '10px', color: '#dc3545' }}>✗ Incorrect</span>
                        )}
                      </div>
                    </label>
                  );
                })}
              </div>

              {submitted && answers[q.id] !== q.correctAnswer && (
                <div
                  style={{
                    marginTop: '15px',
                    padding: '12px',
                    background: '#e7f3ff',
                    borderRadius: '8px',
                    fontSize: '14px',
                    borderLeft: '4px solid #2196f3'
                  }}
                >
                  <strong>💡 Explanation:</strong> {q.explanation}
                </div>
              )}
            </div>
          );
        })}

        <div style={{ display: 'flex', gap: '10px', justifyContent: 'center', marginTop: '20px' }}>
          {!submitted ? (
            <Button 
              onClick={handleSubmit} 
              disabled={Object.keys(answers).length !== quiz.totalQuestions}
              style={{
                opacity: Object.keys(answers).length !== quiz.totalQuestions ? 0.5 : 1,
                cursor: Object.keys(answers).length !== quiz.totalQuestions ? 'not-allowed' : 'pointer'
              }}
            >
              📝 Submit Quiz
            </Button>
          ) : (
            <Button onClick={onClose}>
              Close Quiz
            </Button>
          )}
        </div>

        {!submitted && Object.keys(answers).length !== quiz.totalQuestions && (
          <p style={{ textAlign: 'center', color: '#ff9800', fontSize: '12px', marginTop: '10px' }}>
            ⚠️ Please answer all {quiz.totalQuestions} questions before submitting
          </p>
        )}
      </div>
    </div>
  );
}

export default QuizModal;